---
name: ${NAME}
services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=file:/run/secrets/ts_authkey
      - TS_HOSTNAME=${NAME}
    secrets:
      - ts_authkey
    restart: unless-stopped
  technitium:
    image: docker.io/technitium/dns-server:latest
    environment:
      # note that these values are only used for initializing the system
      # they do not take effect if /etc/dns already exists
      - DNS_SERVER_DOMAIN=${NAME}
      - DNS_SERVER_ADMIN_PASSWORD_FILE=/run/secrets/technitium_password
      - DNS_SERVER_PREFER_IPV6=true
    secrets:
      - technitium_password
    volumes:
      - technitium_data:/etc/dns
    depends_on:
      - tailscale
    network_mode: service:tailscale
    restart: unless-stopped
secrets:
  ts_authkey:
    environment: "TS_AUTHKEY"
  technitium_password:
    environment: "TECHNITIUM_PASSWORD"
volumes:
  technitium_data:
networks:
  default:
    enable_ipv6: true
